Feature/explorer card
mark3d-xyz/mark3d pull request #10
Opened 2022-10-21 14:52 UTC by reversoid

Реализовал таблицу, создал вспомогательные компоненты: swiper (карусель для фотографий), строка таблицы. Таблица генерируется с помощью вспомогательного класса TableBuilder.

2022-10-21 21:04 UTC, Santalov requested changes

2022-10-25 18:46 UTC, Santalov approved these changes

2022-10-27 13:42 UTC, Santalov requested changes

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/TableRow/TableRow.tsx
> +  fontSize: '14px',
Старайся не задавать шрифты так (можно только если это очень сильно упрощает работу).
Там в одной строке на самом деле два варианта начертания текста + у нас в дизайне варианты текста строго заданы, то есть каждый вариант это четверка (ширфт, размер ширфта, жирность, line-height)

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/TableRow/TableRow.tsx
> +    title: {
У тайтла на самом деле еще и шрифт другой

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/TableRow/RowContent.tsx
> +          <Txt h3 css={{ fontSize: '$body1', display: 'block' }}>
это должен быть вариант primary1

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/TableRow/RowContent.tsx
> +          <Txt
это должен быть вариант secondary2

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/TableRow/RowContent.tsx
> +          <Txt h3 css={{ fontSize: '$body2' }}>
это должен быть вариант primary1

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/TableRow/RowContent.tsx
> +          <Button css={{ background: '$gradients$main', color: '$white' }}>
это вариант primary у button, не нужно градиант и цвет руками передавать

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/TableRow/RowContent.tsx
> +  title: string
title должен быть reactNode, потому что в нем обычно лого этого метаверса

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/utils/tableBuilder.tsx
> +  hide: 'sm' | 'md' | 'lg' | 'xl' | false
не круто, что в каждой ячейке надо указывать, на каком размере экрана ее скрывать

2022-10-27 13:42 UTC, Santalov commented on frontend/src/app/components/Table/utils/tableBuilder.tsx
> +  hide: 'sm' | 'md' | 'lg' | 'xl' | false
Давай сделаем так, чтобы в headItems указывалось, какую колонку скрывать целиком

2022-10-31 10:15 UTC, reversoid commented on frontend/src/app/components/Table/TableRow/RowContent.tsx
> +          <Txt h3 css={{ fontSize: '$body1', display: 'block' }}>
жирность не подходит, надо примерно 700, судя по картинке

2022-11-01 13:57 UTC, merged