Feature/history
mark3d-xyz/mark3d pull request #74
Opened 2022-12-02 14:24 UTC by reversoid

updated explorer page

2022-12-06 19:18 UTC, Santalov requested changes

2022-12-07 13:33 UTC, Santalov requested changes

2022-12-07 13:33 UTC, Santalov commented on frontend/src/app/stores/TransfersHistory/TransfersHistoryStore.tsx
> +                  ? Number(transfer.order?.price).toFixed(5)
Цена измеряется в валюте бч, для этого используй formatCurrency утилиту

2022-12-07 13:33 UTC, Santalov commented on frontend/src/app/stores/UserTransfers/UserTransfersStore.ts
> +    price: Number(transfer.order?.price)
Цену нужно форматировать, нельзя ее просто кастовать к строке, так как часто она будет не влезать, там 18 знаков после запятой

2022-12-09 13:58 UTC, Santalov commented on frontend/src/app/pages/ProfilePage/ProfilePage.tsx
> +  }, [nfts, table, transferCards])
там кароч с использованием observable в useEffect прикол https://mobx.js.org/react-integration.html#useeffect

2022-12-09 13:58 UTC, Santalov commented on frontend/src/app/pages/ProfilePage/ProfilePage.tsx
> +  }, [nfts, table, transferCards])
Тут счетчик плохо обновляется из-за этого

2022-12-09 16:00 UTC, reversoid commented on frontend/src/app/pages/ProfilePage/ProfilePage.tsx
> +  }, [nfts, table, transferCards])
тут юзмемо, и плохо обновлялся, пушо не передал profileAddres в хук, оказывается)))

2022-12-09 16:39 UTC, Santalov approved these changes

2022-12-09 16:39 UTC, Santalov commented on frontend/src/app/pages/ProfilePage/ProfilePage.tsx
> +  }, [nfts, table, transferCards])
аааа

2022-12-09 16:39 UTC, merged